# Generated by Django 5.2.5 on 2025-08-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(max_length=100)),
                ('option_d', models.CharField(max_length=100)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('level', models.IntegerField(choices=[(1, 'R$1000'), (2, 'R$2000'), (3, 'R$3000'), (4, 'R$4000'), (5, 'R$5000'), (6, 'R$6000'), (7, 'R$7000'), (8, 'R$8000'), (9, 'R$9000'), (10, 'R$10000'), (11, 'R$11000'), (12, 'R$12000'), (13, 'R$13000'), (14, 'R$14000'), (15, 'R$15000')])),
            ],
        ),
    ]
