# Generated by Django 5.2.5 on 2025-08-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wrong_options',
            field=models.CharField(default='', max_length=3),
        ),
    ]
